# Generated by Django 4.2.3 on 2023-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order_iteminorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
            preserve_default=False,
        ),
    ]
